version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    
    bash --version

    bash -lc "exec 0</dev/null && mount && ls -la /c && find /c/tools/ -iname vcpkg.exe"

    bash -lc "exec 0</dev/null && /c/tools/vcpkg/vcpkg.exe install libzip:x64-windows"
    
