version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    vcpkg update

    cd C:\Tools\vcpkg

    git pull

    echo updated

    vcpkg install libpng:arm-uwp

    vcpkg install freetype:arm-uwp
