version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    
    bash --version

    bash -lc "exec 0</dev/null && which xargs && xargs --version && echo foo bar | xargs -P 2 -n1 echo"
